name: distill

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  render_site:
    runs-on: macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Setup tinytex
        uses: r-lib/actions/setup-tinytex@v1

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: 2.11.4

      - name: Install Packages
        run: Rscript -e 'install.packages("distill")'

      - name: Render Site
        run: |
          Rscript -e 'rmarkdown::clean_site(preview = FALSE)'
          Rscript -e 'rmarkdown::render_site()'
